package com.conexemi.emi.model;

public enum CategoryType {
    TECNOLOGIA,
    ENERGIA_Y_SOSTENIBILIDAD,
    SALUD_Y_BIENESTAR,
    E_COMMERCE,
    ALIMENTOS_Y_BEBIDAS,
    AUTOMOTRIZ,
    DEPORTES,
    CULTURA,
    EDUCACION,
    MODA_Y_BELLEZA,
    CONSTRUCCION_E_INMOBILIARIA,
    OTROS
}
